version: '3'
services:
  rdfstore:
    image: lyrasis/blazegraph:2.1.4
    ports:
      - "9999:8080"
  api:
    build: ./apis
    command: nodemon
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:80"