version: '3'
services:
  sdaas:
    build: ./sdaas
    volumes:
      - ./g0v-kb:/kees
    ports:
      - "9999:8080"
  api:
    build: ./apis
    command: [ "nodemon"]
    volumes:
      - ./apis:/usr/src/app
    ports:
      - "8080:80"
  lodview:
    build: ./lodview
    volumes:
      - ./lodview/conf.ttl:/LodView/src/main/webapp/WEB-INF/
    ports:
      - "8082:8080"
  frontend:
    build: ./frontend
    ports:
      - "80:80"