version: '3'
services:
  sdaas:
    build: ./sdaas
    ports:
      - "9999:8080"
  api:
    build: ./apis
    command: [ "nodemon"]
    ports:
      - "8080:80"
    depends_on:
      - "sdaas"
  lodview:
    build: ./lodview
    ports:
      - "8082:8080"
    depends_on:
      - "sdaas"
  lode:
    build: ./g0v-ap
    ports:
      - "8083:8080"
  router:
    build: ./router
    ports:
      - "80:80"
    depends_on:
      - "sdaas"
      - "lodview"
      - "lode"
      - "api"