version: '3'
services:
  sdaas:
    build: ./sdaas
    ports:
      - "29321:8080"
  api:
    build: ./apis
    ports:
      - "29322:80"
    depends_on:
      - "sdaas"
  lodview:
    image: linkeddatacenter/lodview:1.1.0
    ports:
      - "29329:8080"
    environment:
      - LODVIEW_URISPACE=http://mef.linkeddata.cloud/resource/
      - LODVIEW_URISPACEPREFIX=mef 
      - LODVIEW_SPARQLENDPOINT=http://194.177.121.230:29321/sdaas/sparql
      - LODVIEW_HOMEURL=https://github.com/g0v-it/data-budget
      - LODVIEW_DATALICENSE=Contiene dati pubblicati dal Ministero dell'Economia e Finanze Italiano.
      - LODMAP_HOME_TITLE=Welcome to MEF g0v knowledge base
      - LODVIEW_PUBLICURLPREFIX=http://194.177.121.230:29329/
      - LODEVIEW_HEADERLOGO=https://avatars3.githubusercontent.com/u/42692153?s=80
      - "LODVIEW_DATALICENSE=Dati estratti dal portale <a title='Open BDAP' href='https://bdap-opendata.mef.gov.it/' target='_blank'><img style='vertical-align: middle' width='48' src='https://bdap-opendata.mef.gov.it/sites/default/files/images/logo-open-bdap.PNG'></a> e prodotti della Ragioneria dello Stato con licenza <a href='http://creativecommons.org/licenses/by/3.0' target='_blank'>CC-BY</a>"
    depends_on:
      - "sdaas"