version: '3'
services:
  sdaas:
    build: .
    ports:
      - "29321:8080"
  api:
    image: linkeddatacenter/lodmap2d-api
    ports:
      - "29322:8000"
    depends_on:
      - "sdaas"
  webapp:
    image: linkeddatacenter/lodmap2d
    ports:
      - "29323:8080"
    depends_on:
      - "api"
    environment:
      - LODMAP2D_DATA=http://api:8000/
      