version: '3'
services:
  sdaas:
    build: ./sdaas
    volumes:
      - ./g0v-kb:/kees
    ports:
      - "9999:8080"
  api:
    build: ./apis
    command: [ "nodemon"]
    volumes:
      - ./apis:/usr/src/app
    ports:
      - "8080:80"