version: '3'
services:
  sdaas:
    build: ./sdaas
    volumes:
      - ./sdaas/g0v-it:/kees  
      - ./sdaas/sdaas-bin:/usr/local/bin/sdaas
      - ./sdaas/webapps/root:/var/lib/jetty/webapps/root  
    ports:
      - "9999:8080"
  api:
    build: ./apis
    command: [ "nodemon"]
    volumes:
      - ./apis:/usr/src/app
    ports:
      - "8080:80"